// update_checker.cpp
// Checks the URL defined by WSL2IPFWD_UPDATE_URL (compiled in via update_url.h)
// for a version newer than WSL2IPFWD_VERSION.
//
// Default URL:  https://api.github.com/repos/Xykon/wsl2-ipfwd/releases/latest
// Override:     cmake ... -DWSL2IPFWD_UPDATE_URL=http://localhost:8080/releases/latest
//               (see service/CMakeLists.txt)

#include "update_checker.h"
#include "update_url.h"        // WSL2IPFWD_UPDATE_URL  (generated by configure_file)
#include "version.h"           // WSL2IPFWD_VERSION     (common/ is on include path)
#include <windows.h>
#include <winhttp.h>
#include <nlohmann/json.hpp>
#include <ctime>
#include <cstdio>
#include <cstring>

#pragma comment(lib, "winhttp.lib")

using json = nlohmann::json;

// ---- Tick / CheckNow --------------------------------------------------------

bool UpdateChecker::Tick(bool enabled, int intervalHours, int64_t lastCheckUtc) {
    if (!enabled || intervalHours <= 0) return false;
    auto now         = static_cast<int64_t>(std::time(nullptr));
    auto intervalSec = static_cast<int64_t>(intervalHours) * 3600LL;
    if (now - lastCheckUtc < intervalSec) return false;
    return CheckNow();
}

bool UpdateChecker::CheckNow() {
    lastCheckUtc_ = static_cast<int64_t>(std::time(nullptr));

    std::string latestVersion, downloadUrl;
    if (!FetchLatestRelease(latestVersion, downloadUrl)) {
        lastCheckSucceeded_ = false;
        return false;
    }
    lastCheckSucceeded_ = true;

    if (!IsNewerVersion(latestVersion, WSL2IPFWD_VERSION)) {
        // Running the latest — clear any stale pending notification
        pending_ = {};
        return false;
    }

    pending_ = { true, latestVersion, downloadUrl };
    return true;
}

// ---- WinHTTP fetch ----------------------------------------------------------

bool UpdateChecker::FetchLatestRelease(std::string& outVersion, std::string& outUrl) {
    const wchar_t* kAgent   = L"wsl2ipfwd-update-checker/1.0";
    const DWORD    kTimeout = 8000; // ms for connect / send / receive

    // ---- Parse the compile-time URL ----------------------------------------
    // WinHttpCrackUrl fills host, port, path, and scheme from the literal URL.
    // Using the URL scheme allows transparent switching between HTTPS
    // (production) and plain HTTP (localhost test server).
    URL_COMPONENTS uc        = {};
    uc.dwStructSize          = sizeof(uc);
    wchar_t hostBuf[256]     = {};
    wchar_t pathBuf[1024]    = {};
    uc.lpszHostName          = hostBuf;
    uc.dwHostNameLength      = static_cast<DWORD>(_countof(hostBuf));
    uc.lpszUrlPath           = pathBuf;
    uc.dwUrlPathLength       = static_cast<DWORD>(_countof(pathBuf));

    if (!WinHttpCrackUrl(WSL2IPFWD_UPDATE_URL, 0, 0, &uc)) return false;

    const bool          useHttps = (uc.nScheme == INTERNET_SCHEME_HTTPS);
    const INTERNET_PORT port     = uc.nPort;

    // ---- Open session -------------------------------------------------------
    HINTERNET hSession = WinHttpOpen(kAgent,
        WINHTTP_ACCESS_TYPE_DEFAULT_PROXY,
        WINHTTP_NO_PROXY_NAME, WINHTTP_NO_PROXY_BYPASS, 0);
    if (!hSession) return false;
    WinHttpSetTimeouts(hSession, kTimeout, kTimeout, kTimeout, kTimeout);

    HINTERNET hConnect = WinHttpConnect(hSession, hostBuf, port, 0);
    if (!hConnect) {
        WinHttpCloseHandle(hSession);
        return false;
    }

    DWORD reqFlags = useHttps ? WINHTTP_FLAG_SECURE : 0;
    HINTERNET hRequest = WinHttpOpenRequest(hConnect, L"GET", pathBuf,
        nullptr, WINHTTP_NO_REFERER,
        WINHTTP_DEFAULT_ACCEPT_TYPES, reqFlags);
    if (!hRequest) {
        WinHttpCloseHandle(hConnect);
        WinHttpCloseHandle(hSession);
        return false;
    }

    // GitHub API headers — harmless to send to the local test server
    WinHttpAddRequestHeaders(hRequest,
        L"Accept: application/vnd.github+json\r\n"
        L"X-GitHub-Api-Version: 2022-11-28\r\n",
        static_cast<DWORD>(-1), WINHTTP_ADDREQ_FLAG_ADD);

    bool ok = WinHttpSendRequest(hRequest, WINHTTP_NO_ADDITIONAL_HEADERS, 0,
                                  WINHTTP_NO_REQUEST_DATA, 0, 0, 0)
           && WinHttpReceiveResponse(hRequest, nullptr);

    DWORD httpStatus = 0;
    if (ok) {
        DWORD sz = sizeof(httpStatus);
        WinHttpQueryHeaders(hRequest,
            WINHTTP_QUERY_STATUS_CODE | WINHTTP_QUERY_FLAG_NUMBER,
            WINHTTP_HEADER_NAME_BY_INDEX, &httpStatus, &sz,
            WINHTTP_NO_HEADER_INDEX);
        ok = (httpStatus == 200);
    }

    std::string body;
    if (ok) {
        DWORD avail = 0;
        while (WinHttpQueryDataAvailable(hRequest, &avail) && avail > 0) {
            std::string chunk(avail, '\0');
            DWORD read = 0;
            if (!WinHttpReadData(hRequest, chunk.data(), avail, &read)) break;
            chunk.resize(read);
            body += chunk;
            if (body.size() > 512 * 1024) break; // safety cap
        }
    }

    WinHttpCloseHandle(hRequest);
    WinHttpCloseHandle(hConnect);
    WinHttpCloseHandle(hSession);

    if (!ok || body.empty()) return false;

    try {
        auto j     = json::parse(body);
        outVersion = j.value("tag_name", "");

        // Find the first .exe asset (the setup installer)
        if (j.contains("assets") && j["assets"].is_array()) {
            for (auto& asset : j["assets"]) {
                std::string name = asset.value("name", "");
                if (name.size() >= 4 &&
                    name.compare(name.size() - 4, 4, ".exe") == 0) {
                    outUrl = asset.value("browser_download_url", "");
                    break;
                }
            }
        }
        return !outVersion.empty();
    } catch (...) {
        return false;
    }
}

// ---- Version comparison -----------------------------------------------------

bool UpdateChecker::ParseVersion(const std::string& s, int& major, int& minor, int& patch) {
    const char* p = s.c_str();
    if (*p == 'v' || *p == 'V') ++p;
    return std::sscanf(p, "%d.%d.%d", &major, &minor, &patch) == 3;
}

bool UpdateChecker::IsNewerVersion(const std::string& latest, const std::string& current) {
    int lMaj = 0, lMin = 0, lPat = 0;
    int cMaj = 0, cMin = 0, cPat = 0;
    if (!ParseVersion(latest,  lMaj, lMin, lPat)) return false;
    if (!ParseVersion(current, cMaj, cMin, cPat)) return false;
    if (lMaj != cMaj) return lMaj > cMaj;
    if (lMin != cMin) return lMin > cMin;
    return lPat > cPat;
}
